2019-06-11 23:46:41,732 0    [main] INFO  core.SenderPlatform  - ::>>>????::CONFIG::::

mturl: null
mt_username: null
mt_password: null
THROTTLE: 50
WORKER_THREADS: 2
initialDBConnections: 2
maxDBConnections: 4
queueSize: 10000
pollWait: 100
urlparams: URLParams [CP_Id=null, CP_UserId=null, CP_Password=null, CMP_ContentType=null, CMP_A_Keyword=null, CMP_S_Keyword=null, SMS_Msgdata=null, SMS_SourceAddr=null, SUB_DeviceType=null, SMS_MsgTxt=null, SUB_R_Mobtel=null, SUB_C_Mobtel=null, http_timeout=5000, retry_per_msg=1, msg_part_wait=100, SERVER_TZ=-05:00, CLIENT_TZ=+03:00, mturl=http://41.223.58.157:56000/Bharti, login=content36, pass=content36, type=text, src=32329]
2019-06-11 23:46:41,737 5    [main] ERROR core.OutgoingQueueRouter  - null
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.valueOf(Integer.java:766)
	at com.pixelandtag.sms.core.OutgoingQueueRouter.initialize(OutgoingQueueRouter.java:118)
	at com.pixelandtag.sms.core.OutgoingQueueRouter.<init>(OutgoingQueueRouter.java:111)
	at com.pixelandtag.sms.core.SenderPlatform.main(SenderPlatform.java:100)
2019-06-11 23:46:41,757 25   [main] DEBUG jboss.logging  - Logging Provider: org.jboss.logging.Log4jLoggerProvider
2019-06-11 23:46:41,779 47   [main] DEBUG client.EJBClientPropertiesLoader  - Looking for jboss-ejb-client.properties using classloader sun.misc.Launcher$AppClassLoader@28d93b30
2019-06-11 23:46:41,792 60   [main] DEBUG client.InitialContextFactory  - Looking for jboss-naming-client.properties using classloader sun.misc.Launcher$AppClassLoader@28d93b30
2019-06-11 23:46:41,793 61   [main] DEBUG client.InitialContextFactory  - jboss.naming.client.endpoint.create.options. has the following options {}
2019-06-11 23:46:41,793 61   [main] DEBUG client.InitialContextFactory  - jboss.naming.client.remote.connectionprovider.create.options. has the following options {}
2019-06-11 23:46:41,807 75   [main] INFO  org.xnio  - XNIO version 3.4.1.Final
2019-06-11 23:46:41,814 82   [main] INFO  xnio.nio  - XNIO NIO Implementation Version 3.4.1.Final
2019-06-11 23:46:41,903 171  [Remoting "config-based-naming-client-endpoint" I/O-1] DEBUG xnio.nio  - Started channel thread 'Remoting "config-based-naming-client-endpoint" I/O-1', selector sun.nio.ch.KQueueSelectorImpl@6cb47364
2019-06-11 23:46:41,903 171  [Remoting "config-based-naming-client-endpoint" Accept] DEBUG xnio.nio  - Started channel thread 'Remoting "config-based-naming-client-endpoint" Accept', selector sun.nio.ch.KQueueSelectorImpl@1fcb59e2
2019-06-11 23:46:41,913 181  [main] INFO  jboss.remoting  - JBoss Remoting version (unknown)
2019-06-11 23:46:41,927 195  [main] DEBUG client.InitialContextFactory  - jboss.naming.client.connect.options. has the following options {}
2019-06-11 23:46:41,969 237  [main] DEBUG client.HaRemoteNamingStore  - Failed to connect to server remote://localhost:4447
java.lang.RuntimeException: java.net.ConnectException: Connection refused
	at org.jboss.naming.remote.protocol.IoFutureHelper.get(IoFutureHelper.java:95)
	at org.jboss.naming.remote.client.HaRemoteNamingStore.failOverSequence(HaRemoteNamingStore.java:198)
	at org.jboss.naming.remote.client.HaRemoteNamingStore.namingStore(HaRemoteNamingStore.java:149)
	at org.jboss.naming.remote.client.HaRemoteNamingStore.namingOperation(HaRemoteNamingStore.java:130)
	at org.jboss.naming.remote.client.HaRemoteNamingStore.lookup(HaRemoteNamingStore.java:272)
	at org.jboss.naming.remote.client.RemoteContext.lookupInternal(RemoteContext.java:104)
	at org.jboss.naming.remote.client.RemoteContext.lookup(RemoteContext.java:93)
	at org.jboss.naming.remote.client.RemoteContext.lookup(RemoteContext.java:146)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at com.pixelandtag.sms.core.OutgoingQueueRouter.initEJB(OutgoingQueueRouter.java:177)
	at com.pixelandtag.sms.core.OutgoingQueueRouter.initialize(OutgoingQueueRouter.java:124)
	at com.pixelandtag.sms.core.OutgoingQueueRouter.<init>(OutgoingQueueRouter.java:111)
	at com.pixelandtag.sms.core.SenderPlatform.main(SenderPlatform.java:100)
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.xnio.nio.WorkerThread$ConnectHandle.handleReady(WorkerThread.java:321)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:567)
	at ...asynchronous invocation...(Unknown Source)
	at org.jboss.remoting3.EndpointImpl.doConnect(EndpointImpl.java:272)
	at org.jboss.remoting3.EndpointImpl.doConnect(EndpointImpl.java:253)
	at org.jboss.remoting3.EndpointImpl.connect(EndpointImpl.java:351)
	at org.jboss.remoting3.EndpointImpl.connect(EndpointImpl.java:335)
	at org.jboss.naming.remote.client.EndpointCache$EndpointWrapper.connect(EndpointCache.java:111)
	at org.jboss.naming.remote.client.HaRemoteNamingStore.failOverSequence(HaRemoteNamingStore.java:197)
	... 11 more
